"""initial schema

Revision ID: 41b307bfe8f2
Revises: 
Create Date: 2026-06-16 16:27:37.465124
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import app.models.types  # GUID type (native UUID on Postgres, CHAR(36) elsewhere)


revision: str = '41b307bfe8f2'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shipments',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('origin', sa.String(), nullable=False),
    sa.Column('destination', sa.String(), nullable=False),
    sa.Column('eta', sa.DateTime(timezone=True), nullable=True),
    sa.Column('carrier', sa.String(), nullable=False),
    sa.Column('weight_kg', sa.Numeric(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', app.models.types.GUID(), nullable=False),
    sa.Column('username', sa.String(length=40), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('display_name', sa.String(length=80), nullable=False),
    sa.Column('presence', sa.String(length=10), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('role', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('channels',
    sa.Column('id', app.models.types.GUID(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=True),
    sa.Column('type', sa.String(length=10), nullable=False),
    sa.Column('topic', sa.String(length=255), nullable=True),
    sa.Column('created_by', app.models.types.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('ai_summaries',
    sa.Column('id', app.models.types.GUID(), nullable=False),
    sa.Column('channel_id', app.models.types.GUID(), nullable=False),
    sa.Column('window', sa.String(length=40), nullable=False),
    sa.Column('model', sa.String(length=60), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('source_message_ids', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['channel_id'], ['channels.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('memberships',
    sa.Column('id', app.models.types.GUID(), nullable=False),
    sa.Column('user_id', app.models.types.GUID(), nullable=False),
    sa.Column('channel_id', app.models.types.GUID(), nullable=False),
    sa.Column('role', sa.String(length=10), nullable=False),
    sa.Column('last_read_message_id', sa.BigInteger(), nullable=True),
    sa.Column('joined_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['channel_id'], ['channels.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'channel_id', name='uq_membership')
    )
    op.create_index('ix_membership_channel', 'memberships', ['channel_id'], unique=False)
    op.create_index('ix_membership_user', 'memberships', ['user_id'], unique=False)
    op.create_table('messages',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('channel_id', app.models.types.GUID(), nullable=False),
    sa.Column('sender_id', app.models.types.GUID(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('type', sa.String(length=10), nullable=False),
    sa.Column('client_msg_id', sa.String(length=64), nullable=True),
    sa.Column('reply_to_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('edited_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['channel_id'], ['channels.id'], ),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('channel_id', 'client_msg_id', name='uq_msg_idempotency')
    )
    op.create_index('ix_messages_channel_id', 'messages', ['channel_id', 'id'], unique=False)
    op.create_table('message_shipments',
    sa.Column('id', app.models.types.GUID(), nullable=False),
    sa.Column('message_id', sa.BigInteger(), nullable=False),
    sa.Column('shipment_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], ),
    sa.ForeignKeyConstraint(['shipment_id'], ['shipments.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('message_id', 'shipment_id', name='uq_msg_shipment')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('message_shipments')
    op.drop_index('ix_messages_channel_id', table_name='messages')
    op.drop_table('messages')
    op.drop_index('ix_membership_user', table_name='memberships')
    op.drop_index('ix_membership_channel', table_name='memberships')
    op.drop_table('memberships')
    op.drop_table('ai_summaries')
    op.drop_table('channels')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('shipments')
    # ### end Alembic commands ###
